blank_issues_enabled: false

contact_links:
  - name: Xodex
    url: https://github.com/djoezeke/xodex
    about: Modern GUIs with pygame.

  - name: Xodex Issues | Bug Bounty
    url: https://github.com/djoezeke/xodex/issues
    about: Please report issues and vulnerabilities here.

  - name: Xodex Releases
    url: https://github.com/djoezeke/xodex/releases
    about: Please latest Uinex release here.
