blank_issues_enabled: false

contact_links:
  - name: Xodex Engine 🎮
    url: https://github.com/djoezeke/xodex
    about: Modern Pygame Based Game Framework.

  - name: Xodex Discussions 💖
    url: https://github.com/djoezeke/xodex/discussions
    about: The "Discussions" forum is where you want to start.

  - name: Xodex Issues | Bug Bounty 🐞
    url: https://github.com/djoezeke/xodex/issues
    about: Please report issues and vulnerabilities here.

  - name: Xodex Releases
    url: https://github.com/djoezeke/xodex/releases
    about: Please latest Xodex release here.
