# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Xodex CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: ["main", "dev"]

permissions:
  contents: read

jobs:
  build:
    name: Xodex Lint & Format
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Ruff Xodex Type Checking
        run: uv run ruff check .
      - name: Ruff Xodex Formating
        run: uv run ruff format --diff .
      - name: Prettier Markdown Fromating
        run: npx prettier --prose-wrap always --check "**/*.md"
      - name: Xodex Testing
        run: uv run pytest
